name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  cache-name: build-cache

jobs:
  build:
    name: scripts 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        out_dir: [dist]
        name: [bin]
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: goto-bus-stop/setup-zig@v2

      - uses: actions/cache@v3
        env:
          cache-key: ${{ env.cache-name }}-${{ runner.os }}
        with:
          path: ${{ matrix.out_dir }}
          key: ${{ env.cache-key }}
          restore-keys: ${{ env.cache-key }}

      - name: Build code
        run: scripts/build.sh ${{ matrix.out_dir }} ${{ matrix.name }}

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}
          path: |
            src
            ${{ matrix.out_dir }}
