name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  cache-name: build-cache

jobs:
  build:
    name: scripts 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            out_path: .\dist\bin
          - os: ubuntu-latest
            out_path: ./dist/bin
          - os: macos-latest
            out_path: ./dist/bin

    steps:
      - uses: actions/checkout@v3

      - uses: goto-bus-stop/setup-zig@v2

      - uses: actions/cache@v3
        env:
          cache-key: ${{ env.cache-name }}-${{ runner.os }}
        with:
          path: ${{ matrix.out_path }}
          key: ${{ env.cache-key }}
          restore-keys: ${{ env.cache-key }}

      - name: Build code
        run: scripts/build.sh ${{ matrix.out_path }}

      - uses: actions/upload-artifact@v3
        with:
          name: build-${{ runner.os }}
          path: |
            src
            build
